# Generated by Django 5.1.2 on 2024-10-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ativo',
            table='ativo',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
