# Generated by Django 5.1.2 on 2024-10-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inoa', '0005_remove_ativo_valor_ativo_periodo_checagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='pbkdf2_sha256$870000$CW7Rb7xGQVWU2wZZNO5Kh3$/lR/aYZsolsWUhzBs8N8CwczuqS+HltsIR9BPe7UneE=', max_length=100),
        ),
    ]
