# Generated by Django 5.1.2 on 2024-10-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inoa', '0007_remove_usuario_senha_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$uBuzyA8lRaeYkctRgfFq7t$8Mb6NqRmMj8ZuickUcGks1W7BidBpX3b7VXsyaugEAA=', max_length=100),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
